iframe = document.createElement('iframe');
address = window.location.pathname.split('/')[2];
item = window.location.pathname.split('/')[4];
iframe.src = "https://preview.decentraland.vote?iframe=1&contract=" + address + "&item=" + item;
iframe.style.height = "100%";
iframe.style.width = "50%";
iframe.style.border = "0";
iframe.style.outline = "none";
w = document.getElementsByClassName("rarity-background")[0];
w.appendChild(iframe);